services:
  markdownprocessorweb:
    image: markdownprocessorweb
    build:
      context: .
      dockerfile: MarkdownProcessorWeb/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - s3
    environment:
      - ConnectionStrings:DefaultConnection=Host=localhost;Port=5432;Database=MarkdownProcessor;Username=postgres;Password=1234;;
      - AWS:S3:ServiceURL=http://s3:9000
      - AWS:S3:AccessKey=your_access_key
      - AWS:S3:SecretKey=your_secret_key
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: MarkdownProcessor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: your_access_key
      MINIO_ROOT_PASSWORD: your_secret_key
    volumes:
      - s3_data:/data

volumes:
  postgres_data:
  s3_data: