services:
  markdownprocessorweb:
    image: markdownprocessorweb
    build:
      context: .
      dockerfile: MarkdownProcessorWeb/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - s3
    environment:
      - ConnectionStrings:DefaultConnection=Host=localhost;Port=5432;Database=MarkdownProcessor;Username=postgres;Password=1234;;
      - AWS:S3:ServiceURL=http://127.0.0.1:9000
      - AWS:S3:AccessKey=p2KsogpfaxbMFGTL75jd
      - AWS:S3:SecretKey=6ExsJUsyslH3DlEEyb0T7c0pgO0CIE4yd56zNn2R
      - AWS:S3:BucketName=markdown-documents
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: MarkdownProcessor
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  s3_data: